[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
numpy = "^2.2.2"
seaborn = "^0.13.2"
matplotlib = "^3.10.0"
scikit-learn = "^1.6.1"
xgboost = "^2.1.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

